updated the filtering language feature
aadeshkulkarni/first-issues pull request #36
Opened 2024-08-20 19:56 UTC by sanjay-09

1. As In this repository, we are dealing with the special characters used in the languages like C#,C++.Hence we were not able 
to fetch the langfilter correctly when the langFilter contains the special character.
url: `/api/project?lang=${langFilter}&sort_by=${sortFilter.value}&order=${sortFilter.order}`.

2. So I have encoded the langFilter before fetching the data using the encodeURIComponent() function,
     
![image](https://github.com/user-attachments/assets/5f6cc959-76ee-4663-8de8-90e19d2848ad)

3.Then I have used the filter statement to filter out the records which are coming from the mongoDb,because for an language C we are getting all the records where C is the prefix so I have filtered those records.
![image](https://github.com/user-attachments/assets/7391a4a2-562d-4708-b7c8-823b052319d8)

4.For the language C++, As it contains the extra special Character '++', its regex was not matching while quering the database. So for this I have created a manual regex to match the records where the language is 'C++'
![image](https://github.com/user-attachments/assets/cd050327-8c08-4c71-900b-4c29af0add93)

I have tested out all the cases and getting the records as per the expectation.
![image](https://github.com/user-attachments/assets/187530ff-1be1-472f-9893-0686019b682b)
![image](https://github.com/user-attachments/assets/e5ffecd9-ff3d-49d8-9486-c0355adfc184)

2024-08-21 10:36 UTC, aadeshk-beam commented on .env.local
> +MONGODB_URI=mongodb+srv://vdnh123:abc123456@atlascluster.4qkviv9.mongodb.net/firstIssue
Please remove this configuration

2024-08-22 06:59 UTC, aadeshkulkarni commented on .env.local
> +MONGODB_URI=mongodb+srv://vdnh123:abc123456@atlascluster.4qkviv9.mongodb.net/firstIssue
@sanjay-09 - .env shouldn't contain secrets. Please remove your db connection string.

2024-08-22 07:01 UTC, aadeshkulkarni requested changes
Please fix the PR comment. Everything looks fine.

2024-08-22 14:51 UTC, sanjay-09 commented
Updated the PR Comment.

2024-08-23 10:04 UTC, aadeshkulkarni approved these changes

2024-08-23 10:05 UTC, aadeshkulkarni commented
Thanks for your contribution!

2024-08-23 10:05 UTC, merged